/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bai_4.Views;

import Bai_4.CSDL.Database;
import Bai_4.Models.DiaCD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tuan
 */
public class frmThem_Sua_Xoa_CD extends javax.swing.JFrame {

    /**
     * Creates new form frmTimDiaCD
     */
    public frmThem_Sua_Xoa_CD() {
        initComponents();
    }
    
    public void HienThiDSDiaCD(){
        Vector<DiaCD> danhsach = new Vector<>();
        int ketqua = Bai_4.CSDL.QuanLyCD.TimDiaCD("", danhsach);
        if(ketqua == -1){
            JOptionPane.showMessageDialog(this, "Lỗi kết nối SQL.");
            return;
        }
        if(ketqua == -2){
            JOptionPane.showMessageDialog(this, "Lỗi SQL.");
            return;
        }
        if(ketqua == 0){
            JOptionPane.showMessageDialog(this, "Không tìm thấy Sinh Viên.");
            return;
        }
        DefaultTableModel dtm = (DefaultTableModel) tblDSDiaCD.getModel();
        dtm.setRowCount(0);
        danhsach.forEach((diaCD) -> {
            dtm.addRow(new Object[] {diaCD.getTenCD(), diaCD.getCaSy(), diaCD.getSoBaiHat(), diaCD.getGia()});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTenCD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenCaSy = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoBaiHat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        btnThemCD = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTimTenCD = new javax.swing.JTextField();
        btnTimCD = new javax.swing.JButton();
        btnXoaCD = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSDiaCD = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel2.setText("Tên CD:");

        jLabel3.setText("Tên ca sỹ:");

        jLabel4.setText("Số bài hát:");

        jLabel5.setText("Giá:");

        btnThemCD.setText("THÊM CD");
        btnThemCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenCD, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoBaiHat, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenCaSy, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btnThemCD, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenCD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenCaSy, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoBaiHat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(btnThemCD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thêm đĩa CD", jPanel1);

        jLabel1.setText("Tên CD");

        btnTimCD.setText("Search");
        btnTimCD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimCDMouseClicked(evt);
            }
        });
        btnTimCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimCDActionPerformed(evt);
            }
        });

        btnXoaCD.setText("Delete");
        btnXoaCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCDActionPerformed(evt);
            }
        });

        tblDSDiaCD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên CD", "Ca sỹ", "Số bài hát", "Giá"
            }
        ));
        jScrollPane1.setViewportView(tblDSDiaCD);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimTenCD, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTimCD)
                        .addGap(48, 48, 48)
                        .addComponent(btnXoaCD, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTimTenCD, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaCD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimCD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Tìm đĩa CD", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimCDActionPerformed
        // TODO add your handling code here:
        Vector<DiaCD> danhsach = new Vector<DiaCD>();
        String tenCD = this.txtTimTenCD.getText();
        if(tenCD.equals("")){
            JOptionPane.showMessageDialog(this, "Chưa nhập tên CD cần tìm.");
            return;
        }
        int ketqua = Bai_4.CSDL.QuanLyCD.TimDiaCD(tenCD, danhsach);
        if(ketqua == -2){
            JOptionPane.showMessageDialog(this, "Lỗi liên kết SQL.");
            return;
        }
        if(ketqua == -1){
            JOptionPane.showMessageDialog(this, "Lỗi SQL.");
            return;
        }
        if(ketqua == 0){
            JOptionPane.showMessageDialog(this, "Không tìm thấy CD.");
            return;
        }
        DefaultTableModel dtm = (DefaultTableModel) tblDSDiaCD.getModel();
        dtm.setRowCount(0);
        danhsach.forEach((diaCD) -> {
            dtm.addRow(new Object[] {diaCD.getTenCD(), diaCD.getCaSy(), diaCD.getSoBaiHat(), diaCD.getGia()});
        });
        
    }//GEN-LAST:event_btnTimCDActionPerformed

    private void btnTimCDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimCDMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnTimCDMouseClicked

    private void btnXoaCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCDActionPerformed
        // TODO add your handling code here:
        int i = this.tblDSDiaCD.getSelectedRow();
        if(i < 0){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn CD để Xóa.");
            return;
        }
        DefaultTableModel dtm = (DefaultTableModel) tblDSDiaCD.getModel();
        String tenCD = (String) dtm.getValueAt(i, 0);
        int res = JOptionPane.showConfirmDialog(this, "Xóa CD", "Chắc chắn Xóa CD.?", JOptionPane.YES_NO_CANCEL_OPTION);
        
        if(res == JOptionPane.YES_OPTION){
            int ketqua = Bai_4.CSDL.QuanLyCD.XoaDiaCD(tenCD);
            if(ketqua == -1){
                JOptionPane.showMessageDialog(this, "Lỗi Kết nối SQL.");
                return;
            }
            if(ketqua == -2){
                JOptionPane.showMessageDialog(this, "Lỗi SQL rồi.");
                return;
            }
            if(ketqua == 0){
                JOptionPane.showMessageDialog(this, "Xóa Không thành cồng bạn ơi.");
                return;
            }
            if(ketqua > 0){
                JOptionPane.showMessageDialog(this, "Xóa CD thành công.");
                HienThiDSDiaCD();
            }
        }
    }//GEN-LAST:event_btnXoaCDActionPerformed

    private void btnThemCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCDActionPerformed
        // TODO add your handling code here:
        String tenCD = this.txtTenCD.getText();
        String caSy = this.txtTenCaSy.getText();
        String soBaiHat = this.txtSoBaiHat.getText();
        String gia = this.txtGia.getText();
        
        if(tenCD.equals("")){
            JOptionPane.showMessageDialog(this, "Chưa nhập tên CD.");
            return;
        }
        if(caSy.equals("")){
            JOptionPane.showMessageDialog(this, "Chưa nhập ca sỹ.");
            return;
        }
        if(gia.equals("")){
            JOptionPane.showMessageDialog(this, "Chưa nhập giá.");
            return;
        }
        int intSoBH = (int)Integer.parseInt(soBaiHat);
        double doubleGia = (double)Double.parseDouble(gia);
        
        DiaCD diaCD = new DiaCD(tenCD, caSy, intSoBH, doubleGia);
        int ketqua = Bai_4.CSDL.QuanLyCD.ThemDiaCD(diaCD);
        if(ketqua == -1){
            JOptionPane.showMessageDialog(this, "Lỗi Kết nối SQL.");
            return;
        }
        if(ketqua == -2){
            JOptionPane.showMessageDialog(this, "Lỗi SQL eoeo.");
            return;
        }
        if(ketqua == 0){
            JOptionPane.showMessageDialog(this, "Thêm CD không thành công.");
            return;
        }
        if(ketqua > 0){
            JOptionPane.showMessageDialog(this, "Thêm CD thành công.");
        }
        
    }//GEN-LAST:event_btnThemCDActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        HienThiDSDiaCD();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmThem_Sua_Xoa_CD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmThem_Sua_Xoa_CD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmThem_Sua_Xoa_CD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmThem_Sua_Xoa_CD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmThem_Sua_Xoa_CD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemCD;
    private javax.swing.JButton btnTimCD;
    private javax.swing.JButton btnXoaCD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblDSDiaCD;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtSoBaiHat;
    private javax.swing.JTextField txtTenCD;
    private javax.swing.JTextField txtTenCaSy;
    private javax.swing.JTextField txtTimTenCD;
    // End of variables declaration//GEN-END:variables
}
